#!/usr/bin/env python3
"""
Golden Test Vector Generator
=============================
生成 FMA 的"标准答案"测试向量。

工作原理:
  1. 用 Python 模型 (fma_model.py) 算一遍 → 得到"标准答案"
  2. 把标准答案和输入一起保存
  3. Verilog testbench 读这些向量，比较 RTL 输出是否和标准答案一致

相当于: 老师先做好答案，学生（RTL）来做题，然后对答案。
"""

import sys
import os
import random
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + '/../python')

from fma_model import (
    fp32_pack, fp32_unpack, fp32_value, fp32_fma, fp32_is_nan, fp32_is_inf,
    fp16_pack, fp16_unpack, fp16_value,
    fp8_pack, fp8_unpack,
    int8_mad
)


def gen_fp32_vectors(n=100):
    """生成 FP32 FMA 测试向量

    输出格式 (每行): A_hex B_hex C_hex expected_hex
    """
    vectors = []

    # ---- 边界条件（最重要！）----
    specials = [
        # (A, B, C): 覆盖各种特殊值组合
        (0x3F800000, 0x3F800000, 0x00000000),  # 1*1+0=1
        (0x40000000, 0x40400000, 0x40800000),  # 2*3+4=10
        (0x00000000, 0x3F800000, 0x00000000),  # 0*1+0=0
        (0x3F800000, 0x00000000, 0x3F800000),  # 1*0+1=1
        (0x7FC00000, 0x3F800000, 0x00000000),  # NaN*1+0=NaN
        (0x00000000, 0x7F800000, 0x00000000),  # 0*Inf+0=NaN
        (0x3F800000, 0x7F800000, 0x00000000),  # 1*Inf+0=Inf
        (0x7F800000, 0x3F800000, 0xFF800000),  # Inf*1+(-Inf)=NaN
        (0x3F800000, 0x3F800000, 0x7FC00000),  # 1*1+NaN=NaN
        (0x00800000, 0x00800000, 0x00000000),  # 次正规数
    ]
    for a, b, c in specials:
        expected = fp32_fma(a, b, c)
        vectors.append((a, b, c, expected))

    # ---- 随机向量 ----
    for _ in range(n - len(specials)):
        # 生成随机但有效的 FP32 值
        s = random.randint(0, 1)
        e = random.randint(1, 254)  # 避免 0 和 255（特殊值）
        m = random.randint(0, (1 << 23) - 1)
        a = (s << 31) | (e << 23) | m
        s = random.randint(0, 1)
        e = random.randint(1, 254)
        m = random.randint(0, (1 << 23) - 1)
        b = (s << 31) | (e << 23) | m
        s = random.randint(0, 1)
        e = random.randint(1, 254)
        m = random.randint(0, (1 << 23) - 1)
        c = (s << 31) | (e << 23) | m
        expected = fp32_fma(a, b, c)
        vectors.append((a, b, c, expected))

    return vectors


def gen_fp16_vectors(n=50):
    """生成 FP16 测试向量"""
    vectors = []
    specials = [
        (0x3C00, 0x3C00, 0x0000),  # 1*1+0=1
        (0x4000, 0x4200, 0x4400),  # 2*3+4=10
        (0x7E00, 0x3C00, 0x0000),  # NaN*1+0=NaN
    ]
    import math
    for a, b, c in specials:
        av = fp16_value(a)
        bv = fp16_value(b)
        cv = fp16_value(c)
        if math.isnan(av) or math.isnan(bv) or math.isnan(cv):
            expected = 0x7E00  # NaN
        else:
            result = av * bv + cv
            expected = float_to_fp16_py(result)
        vectors.append((a, b, c, expected))

    return vectors


def gen_int8_vectors(n=30):
    """生成 INT8 MAD 测试向量"""
    vectors = []
    specials = [
        (2, 3, 4, 10),
        (10, 10, 0, 100),
        (-1, 2, 5, 3),
        (127, 127, 0, 16129),
        (-128, 1, 0, -128),
        (0, 0, 0, 0),
    ]
    for a, b, c, expected in specials:
        vectors.append((a, b, c, expected))

    for _ in range(n - len(specials)):
        a = random.randint(-128, 127)
        b = random.randint(-128, 127)
        c = random.randint(-32768, 32767)
        expected = int8_mad(a, b, c)
        vectors.append((a, b, c, expected))

    return vectors


def float_to_fp16_py(f):
    """Python float → FP16 (simplified), handles NaN/Inf"""
    import math
    if math.isnan(f):
        return 0x7E00  # FP16 NaN
    if math.isinf(f):
        return 0x7C00 if f > 0 else 0xFC00  # FP16 Inf
    if f == 0.0:
        return 0
    s = 0
    if f < 0:
        s = 1
        f = -f
    e_raw = int(math.floor(math.log2(f)))
    exp = e_raw + 15
    if exp >= 31:
        return (s << 15) | (31 << 10)  # Inf
    if exp <= 0:
        return s << 15  # underflow to zero
    mantissa = int((f / (2 ** e_raw) - 1.0) * 1024 + 0.5)
    if mantissa >= 1024:
        exp += 1
        mantissa = 0
    return (s << 15) | (exp << 10) | mantissa


def save_vectors(filename, vectors, fmt):
    """保存测试向量到文件"""
    with open(filename, 'w') as f:
        f.write("# Golden test vectors generated by gen_vectors.py\n")
        f.write(f"# Format: {fmt}\n")
        f.write(f"# Count: {len(vectors)}\n\n")
        for v in vectors:
            f.write(' '.join(str(x) for x in v) + '\n')
    print(f"  Saved {len(vectors)} vectors to {filename}")


def main():
    print("=" * 50)
    print("FMA Golden Vector Generator")
    print("=" * 50)

    os.makedirs("vectors", exist_ok=True)

    # FP32 vectors
    print("\n[FP32]")
    fp32_vecs = gen_fp32_vectors(100)
    save_vectors("vectors/fp32_vectors.txt", fp32_vecs, "A_hex B_hex C_hex expected_hex")

    # FP16 vectors
    print("\n[FP16]")
    fp16_vecs = gen_fp16_vectors(50)
    save_vectors("vectors/fp16_vectors.txt", fp16_vecs, "A_hex B_hex C_hex expected_hex")

    # INT8 vectors
    print("\n[INT8]")
    int8_vecs = gen_int8_vectors(30)
    save_vectors("vectors/int8_vectors.txt", int8_vecs, "a_int8 b_int8 c_int16 expected_int16")

    print(f"\nTotal: {len(fp32_vecs)+len(fp16_vecs)+len(int8_vecs)} vectors generated")
    print("\n=== Done ===")


if __name__ == "__main__":
    main()
